apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: simpletask
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: simpletask
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: simpletask.py
            imagePullPolicy: 
            name: simpletask
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/5 * * *'
status: {}
